# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MetadataForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Data(object):
    def setupUi(self, Data):
        Data.setObjectName("Data")
        Data.resize(401, 285)
        self.btnBox = QtWidgets.QDialogButtonBox(Data)
        self.btnBox.setGeometry(QtCore.QRect(10, 230, 371, 32))
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnBox.setObjectName("btnBox")
        self.txbName = QtWidgets.QLineEdit(Data)
        self.txbName.setGeometry(QtCore.QRect(10, 30, 371, 20))
        self.txbName.setObjectName("txbName")
        self.label = QtWidgets.QLabel(Data)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Data)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_2.setObjectName("label_2")
        self.txbValue = QtWidgets.QLineEdit(Data)
        self.txbValue.setGeometry(QtCore.QRect(10, 80, 371, 20))
        self.txbValue.setObjectName("txbValue")
        self.label_3 = QtWidgets.QLabel(Data)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_3.setObjectName("label_3")
        self.txbType = QtWidgets.QLineEdit(Data)
        self.txbType.setGeometry(QtCore.QRect(10, 130, 371, 20))
        self.txbType.setObjectName("txbType")
        self.cbRowType = QtWidgets.QComboBox(Data)
        self.cbRowType.setGeometry(QtCore.QRect(10, 180, 371, 22))
        self.cbRowType.setObjectName("cbRowType")
        self.cbRowType.addItem("")
        self.cbRowType.addItem("")

        self.retranslateUi(Data)
        self.btnBox.accepted.connect(Data.accept)
        self.btnBox.rejected.connect(Data.reject)
        QtCore.QMetaObject.connectSlotsByName(Data)

    def retranslateUi(self, Data):
        _translate = QtCore.QCoreApplication.translate
        Data.setWindowTitle(_translate("Data", "Data Edit"))
        self.label.setText(_translate("Data", "Name"))
        self.label_2.setText(_translate("Data", "Value"))
        self.label_3.setText(_translate("Data", "Type"))
        self.cbRowType.setItemText(0, _translate("Data", "ContentData"))
        self.cbRowType.setItemText(1, _translate("Data", "MetaData"))
